/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.Validador;
import javax.swing.JOptionPane;
import Datos.Cliente;
import Datos.GuardarDatos;


/**
 *
 * @author WINDOWS 10
 */
public class VentanaIngresarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaIngresarCliente
     */
    public VentanaIngresarCliente() {
        initComponents();
        this.setSize(601, 429);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoRut = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 330, 140, 50);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(150, 330, 140, 50);

        jLabel1.setText("Nombre :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 90, 90, 40);

        jLabel4.setText("Rut :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 30, 80, 30);

        jLabel5.setText("Contacto :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 160, 90, 40);

        textoRut.setText("(Ingresar rut con puntos y guion.)");
        textoRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRutActionPerformed(evt);
            }
        });
        getContentPane().add(textoRut);
        textoRut.setBounds(180, 40, 260, 40);

        textoNombre.setText("(Ingresar nombre con la primera mayuscula.)");
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textoNombre);
        textoNombre.setBounds(180, 100, 260, 40);

        textoContacto.setText("(Ejemplo : 912345678)");
        getContentPane().add(textoContacto);
        textoContacto.setBounds(180, 160, 260, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Fondo pantallas 4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -30, 660, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       VentanaDatos ventanaDatos = new VentanaDatos();
         dispose();
         ventanaDatos.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //no tocar este metodo
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
      Validador val = new Validador();
      GuardarDatos gd = new GuardarDatos();
      String nombre , rut , contacto ;
      nombre = textoNombre.getText(); 
        if (!val.validarNombre(nombre)){
        JOptionPane.showMessageDialog(this,"Asegurese de estar ingresando un nombre correcto(La primera letra tiene que ser Mayuscula)");                            
        }
        rut =textoRut.getText(); 
        if (!val.validarRut(rut)){
            JOptionPane.showMessageDialog(this,"Asegurese de estar ingresando un rut correcto)");                            
        }
        contacto = textoContacto.getText();
        if (!val.validarContacto(contacto)){
            JOptionPane.showMessageDialog(this,"Asegurese de estar ingresando un numero correcto");                            
        }
        if(!val.validarNombre(nombre)||!val.validarRut(rut)||!val.validarContacto(contacto)){
            JOptionPane.showMessageDialog(this,"No se ha guardado.");
        }else{
        gd.guardarCliente(rut,nombre,contacto);
        JOptionPane.showMessageDialog(this,"Se guardo correctamente.");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRutActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIngresarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textoContacto;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoRut;
    // End of variables declaration//GEN-END:variables
}
