/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
/**
 *
 * @author WINDOWS 10
 */
public class VentanaDatos extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaDatos
     */
    public VentanaDatos() {
        initComponents();
        this.setSize(484,457);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarCliente = new javax.swing.JButton();
        agregarCotizacion = new javax.swing.JButton();
        mostrarCliente = new javax.swing.JButton();
        mostrarCotizacion = new javax.swing.JButton();
        imagenAgregarCliente = new javax.swing.JLabel();
        imagenMostrarCliente = new javax.swing.JLabel();
        imagenMostrarCotizacion = new javax.swing.JLabel();
        imagenAgregarCotizacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        agregarCliente.setText("Agregar");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCliente);
        agregarCliente.setBounds(70, 173, 90, 30);

        agregarCotizacion.setText("Agregar");
        agregarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCotizacionActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCotizacion);
        agregarCotizacion.setBounds(320, 173, 100, 30);

        mostrarCliente.setText("Mostrar");
        mostrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarCliente);
        mostrarCliente.setBounds(80, 393, 90, 30);

        mostrarCotizacion.setText("Mostrar");
        mostrarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCotizacionActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarCotizacion);
        mostrarCotizacion.setBounds(330, 390, 90, 30);

        imagenAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Icono Cliente.jpg"))); // NOI18N
        getContentPane().add(imagenAgregarCliente);
        imagenAgregarCliente.setBounds(0, -10, 240, 240);

        imagenMostrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Buscar Cliente.jpg"))); // NOI18N
        getContentPane().add(imagenMostrarCliente);
        imagenMostrarCliente.setBounds(0, 220, 240, 220);

        imagenMostrarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Icono Cotizacion.png"))); // NOI18N
        getContentPane().add(imagenMostrarCotizacion);
        imagenMostrarCotizacion.setBounds(110, 0, 370, 220);

        imagenAgregarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Buscar Cotizacion.png"))); // NOI18N
        getContentPane().add(imagenAgregarCotizacion);
        imagenAgregarCotizacion.setBounds(220, 220, 260, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
           VentanaIngresarCliente ventana1 = new VentanaIngresarCliente();
           ventana1.setVisible(true);
           dispose();
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void mostrarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCotizacionActionPerformed
           VentanaMostrarCotizacion ventana4 = new VentanaMostrarCotizacion();
           ventana4.setVisible(true);
           dispose();
    }//GEN-LAST:event_mostrarCotizacionActionPerformed

    private void mostrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarClienteActionPerformed
           VentanaMostrarCliente ventana2 = new VentanaMostrarCliente();
           ventana2.setVisible(true);
           dispose();
    }//GEN-LAST:event_mostrarClienteActionPerformed

    private void agregarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCotizacionActionPerformed
           VentanaAgregarCotizacion ventana3 = new VentanaAgregarCotizacion ();
           ventana3.setVisible(true);
           dispose();
    }//GEN-LAST:event_agregarCotizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCliente;
    private javax.swing.JButton agregarCotizacion;
    private javax.swing.JLabel imagenAgregarCliente;
    private javax.swing.JLabel imagenAgregarCotizacion;
    private javax.swing.JLabel imagenMostrarCliente;
    private javax.swing.JLabel imagenMostrarCotizacion;
    private javax.swing.JButton mostrarCliente;
    private javax.swing.JButton mostrarCotizacion;
    // End of variables declaration//GEN-END:variables
}
    
        
    

